# Generated by Django 5.0 on 2025-01-19 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='phone_number',
            field=models.CharField(default='9812345678', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
