# Generated by Django 5.0 on 2025-01-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0002_donor_email_donor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
