# Generated by Django 5.0 on 2025-01-20 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0002_donor_email_donor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemember',
            name='c_id',
            field=models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.CASCADE, to='mandir.committee'),
        ),
    ]
