# Generated by Django 5.0 on 2025-01-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0003_alter_donor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donated_date',
            field=models.DateField(null=True),
        ),
    ]
