# Generated by Django 5.0 on 2025-01-20 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0003_alter_committeemember_c_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='blog_image/')),
                ('created_at', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_id', models.ForeignKey(db_column='content_id', on_delete=django.db.models.deletion.CASCADE, to='mandir.content')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('event_date', models.DateTimeField()),
                ('images', models.ImageField(upload_to='event_images/')),
                ('description', models.TextField()),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandir.content')),
            ],
        ),
        migrations.CreateModel(
            name='mission_vision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('content_id', models.ForeignKey(db_column='content_id', on_delete=django.db.models.deletion.CASCADE, to='mandir.content')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='notice_image')),
                ('content_id', models.ForeignKey(db_column='content_id', on_delete=django.db.models.deletion.CASCADE, to='mandir.content')),
            ],
        ),
    ]
