# Generated by Django 5.0 on 2025-01-20 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0004_alter_donor_donated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDonor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(default='9812345678', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('email', models.EmailField(max_length=254, null=True)),
                ('image', models.ImageField(upload_to='donor_images/')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donated_date', models.DateField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Donor',
            new_name='BeADonor',
        ),
        migrations.DeleteModel(
            name='DonorImage',
        ),
    ]
